### ISSUE TITLE
Thief gamerule can cause round start exception

### ISSUE THREAD

**Issue by Radezolid** [DeltaV-Station/Delta-v#1407]
## Description
Nukie rounds sometimes just errors out and begins the next round.
Report this for anyone with access to logs. I understand this isn't much information to work with but I didn't see any similar issue registered here.
Attached some screenshots of rounds that instantly died.

**Reproduction**
Got no idea, some nukie rounds just work some do not.

**Screenshots**
![image](https://github.com/DeltaV-Station/Delta-v/assets/170836000/c1f423e2-fc27-4836-947f-756c8643399d)
![image](https://github.com/DeltaV-Station/Delta-v/assets/170836000/f0c3666c-7ae0-4f2b-a159-db707a6c240a)
![image](https://github.com/DeltaV-Station/Delta-v/assets/170836000/ef6e1551-2215-4550-a29f-d2d0fa55ce8c)

**Additional context**
None.

**Comment by deltanedas** [comment]
really need logs to try fix this it happened again today #13185 on apo

**Comment by Axionyxx** [comment]
<details>
  <summary>Exception that triggered the restart</summary>
  
```plaintext
Caught exception in GameTicker
System.InvalidOperationException: Attempted to make VileSlugcat antagonist in gamerule  (959183/n959183, Thief) but there was no valid entity for player.
   at Content.Server.Antag.AntagSelectionSystem.MakeAntag(Entity`1 ent, ICommonSession session, AntagSelectionDefinition def, Boolean ignoreSpawner) in /home/runner/work/Delta-v/Delta-v/Content.Server/Antag/AntagSelectionSystem.cs:line 291
   at Content.Server.Antag.AntagSelectionSystem.ChooseAntags(Entity`1 ent, IList`1 pool, AntagSelectionDefinition def, Boolean midround) in /home/runner/work/Delta-v/Delta-v/Content.Server/Antag/AntagSelectionSystem.cs:line 243
   at Content.Server.Antag.AntagSelectionSystem.ChooseAntags(Entity`1 ent, IList`1 pool, Boolean midround) in /home/runner/work/Delta-v/Delta-v/Content.Server/Antag/AntagSelectionSystem.cs:line 198
   at Content.Server.Antag.AntagSelectionSystem.OnJobsAssigned(RulePlayerJobsAssignedEvent args) in /home/runner/work/Delta-v/Delta-v/Content.Server/Antag/AntagSelectionSystem.cs:line 111
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs) in /home/runner/work/Delta-v/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 335
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent[T](EventSource source, T toRaise) in /home/runner/work/Delta-v/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 275
   at Content.Server.GameTicking.GameTicker.SpawnPlayers(List`1 readyPlayers, Dictionary`2 profiles, Boolean force) in /home/runner/work/Delta-v/Delta-v/Content.Server/GameTicking/GameTicker.Spawning.cs:line 122
   at Content.Server.GameTicking.GameTicker.StartRound(Boolean force) in /home/runner/work/Delta-v/Delta-v/Content.Server/GameTicking/GameTicker.RoundFlow.cs:line 278
 Catcher=GameTicker Sawmill=runtime
 ```
 </details>
 
 <details>
 <summary>Start to end logs</summary>
 
 ```plaintext
<!--StartFragment-->
2024-06-30 19:19:32.829 | Wiping all minds  Sawmill=system.mind |  
-- | -- | --
  |   | 2024-06-30 19:19:32.824 | Restarting round!  Sawmill=ticker |  
  |   | 2024-06-30 19:19:32.824 | Replay recording stopped!  Sawmill=replay |  
  |   | 2024-06-30 19:19:32.824 | Caught exception in GameTicker System.InvalidOperationException: Attempted to make VileSlugcat antagonist in gamerule  (959183/n959183, Thief) but there was no valid entity for player.    at Content.Server.Antag.AntagSelectionSystem.MakeAntag(Entity`1 ent, ICommonSession session, AntagSelectionDefinition def, Boolean ignoreSpawner) in /home/runner/work/Delta-v/Delta-v/Content.Server/Antag/AntagSelectionSystem.cs:line 291    at Content.Server.Antag.AntagSelectionSystem.ChooseAntags(Entity`1 ent, IList`1 pool, AntagSelectionDefinition def, Boolean midround) in /home/runner/work/Delta-v/Delta-v/Content.Server/Antag/AntagSelectionSystem.cs:line 243    at Content.Server.Antag.AntagSelectionSystem.ChooseAntags(Entity`1 ent, IList`1 pool, Boolean midround) in /home/runner/work/Delta-v/Delta-v/Content.Server/Antag/AntagSelectionSystem.cs:line 198    at Content.Server.Antag.AntagSelectionSystem.OnJobsAssigned(RulePlayerJobsAssignedEvent args) in /home/runner/work/Delta-v/Delta-v/Content.Server/Antag/AntagSelectionSystem.cs:line 111    at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs) in /home/runner/work/Delta-v/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 335    at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent[T](EventSource source, T toRaise) in /home/runner/work/Delta-v/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 275    at Content.Server.GameTicking.GameTicker.SpawnPlayers(List`1 readyPlayers, Dictionary`2 profiles, Boolean force) in /home/runner/work/Delta-v/Delta-v/Content.Server/GameTicking/GameTicker.Spawning.cs:line 122    at Content.Server.GameTicking.GameTicker.StartRound(Boolean force) in /home/runner/work/Delta-v/Delta-v/Content.Server/GameTicking/GameTicker.RoundFlow.cs:line 278  Catcher=GameTicker Sawmill=runtime |  
  |   | 2024-06-30 19:19:32.824 | Exception caught while trying to start the round! Restarting round...  Sawmill=ticker |  
  |   | 2024-06-30 19:19:32.823 | Session puff_JOOB transferred to entity 1022126.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.818 | Session EmptyFenrir transferred to entity 1022072.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.809 | Session AdvancedAI transferred to entity 1021930.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.802 | Session KrissTorrio transferred to entity 1021844.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.795 | Session pyromaniack137 transferred to entity 1021776.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.789 | Session Shamiko transferred to entity 1021711.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.783 | Session Noguchi47 transferred to entity 1021613.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.774 | Session Thanik transferred to entity 1021537.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.766 | Session deltanedas transferred to entity 1021463.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.759 | Session Houtkop6 transferred to entity 1021386.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.752 | Session StellaArcturus transferred to entity 1021300.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.744 | Session Archylle transferred to entity 1021225.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.737 | Session Squishy77 transferred to entity 1021158.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.731 | Session Rosethefurry transferred to entity 1021090.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.725 | Session Tynerd transferred to entity 1021021.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.719 | Session Shenoy transferred to entity 1020952.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.714 | Session Aeng transferred to entity 1020880.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.708 | Session djvirus transferred to entity 1020796.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.701 | Session Dauriel transferred to entity 1020658.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.689 | Session PinkBlood transferred to entity 1020590.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.683 | Session scarrlet transferred to entity 1020475.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.674 | Session TechnicFighter transferred to entity 1020390.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.668 | Session DisposableCrewmember42 transferred to entity 1020318.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.662 | Session artian transferred to entity 1020243.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.655 | Session Maximust transferred to entity 1020166.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.648 | Session Romp_ehull transferred to entity 1020072.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.640 | Session Astralus transferred to entity 1019979.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.633 | Session lobstercat transferred to entity 1019922.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.627 | Session makeawishkid transferred to entity 1019830.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.619 | Session Yaytso transferred to entity 1019744.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.612 | Session Zystical654 transferred to entity 1019648.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.603 | Session LTownDown67 transferred to entity 1019542.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.593 | Session N4N0B1T3 transferred to entity 1019474.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.587 | Session Gentlemandestroyer transferred to entity 1019455.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.585 | Session AutumnReign transferred to entity 1019385.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.579 | Session CyberCheburek transferred to entity 1019309.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.573 | Session Stop_Sign transferred to entity 1019236.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.567 | Session EggEater25 transferred to entity 1019179.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.562 | Session Porto transferred to entity 1019080.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.554 | Session Vexy776 transferred to entity 1018991.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.546 | Session Dolphbin transferred to entity 1018910.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.539 | Session DocAnimal transferred to entity 1018832.  Sawmill=system.mind |  
  |   | 2024-06-30 19:19:32.532 | Session Pheonixues transferred to entity 1018753.  Sawmill=system.mind |  
[...]
  |   | 2024-06-30 19:19:31.031 | Started game rule  (959183/n959183, Thief)  Sawmill=ticker |  
[...]
  |   | 2024-06-30 19:19:31.030 | Starting round!  Sawmill=ticker

<!--EndFragment-->
```

</details>

I don't see how the mentioned player caused the issue, as there aren't any other exceptions, and it does seem to indicate they were ready, but it also doesn't look like an attempt to spawn them was made

<details>
<summary>All logs mentioning VileSlugcat leading up to the exception</summary>

```plaintext
<!--StartFragment-->
2024-06-30 19:19:32.824 | Caught exception in GameTicker System.InvalidOperationException: Attempted to make VileSlugcat antagonist in gamerule  (959183/n959183, Thief) but there was no valid entity for player.    at Content.Server.Antag.AntagSelectionSystem.MakeAntag(Entity`1 ent, ICommonSession session, AntagSelectionDefinition def, Boolean ignoreSpawner) in /home/runner/work/Delta-v/Delta-v/Content.Server/Antag/AntagSelectionSystem.cs:line 291    at Content.Server.Antag.AntagSelectionSystem.ChooseAntags(Entity`1 ent, IList`1 pool, AntagSelectionDefinition def, Boolean midround) in /home/runner/work/Delta-v/Delta-v/Content.Server/Antag/AntagSelectionSystem.cs:line 243    at Content.Server.Antag.AntagSelectionSystem.ChooseAntags(Entity`1 ent, IList`1 pool, Boolean midround) in /home/runner/work/Delta-v/Delta-v/Content.Server/Antag/AntagSelectionSystem.cs:line 198    at Content.Server.Antag.AntagSelectionSystem.OnJobsAssigned(RulePlayerJobsAssignedEvent args) in /home/runner/work/Delta-v/Delta-v/Content.Server/Antag/AntagSelectionSystem.cs:line 111    at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs) in /home/runner/work/Delta-v/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 335    at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent[T](EventSource source, T toRaise) in /home/runner/work/Delta-v/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 275    at Content.Server.GameTicking.GameTicker.SpawnPlayers(List`1 readyPlayers, Dictionary`2 profiles, Boolean force) in /home/runner/work/Delta-v/Delta-v/Content.Server/GameTicking/GameTicker.Spawning.cs:line 122    at Content.Server.GameTicking.GameTicker.StartRound(Boolean force) in /home/runner/work/Delta-v/Delta-v/Content.Server/GameTicking/GameTicker.RoundFlow.cs:line 278  Catcher=GameTicker Sawmill=runtime |  
-- | -- | --
  |   | 2024-06-30 19:18:45.583 | VileSlugcat:vote 1 4  Sawmill=con |  
  |   | 2024-06-30 19:16:57.136 | VileSlugcat:toggleready True  Sawmill=con |  
  |   | 2024-06-30 19:16:41.617 | VileSlugcat:toggleready False  Sawmill=con |  
  |   | 2024-06-30 19:16:40.786 | VileSlugcat:toggleready True  Sawmill=con |  
  |   | 2024-06-30 19:16:32.520 | Sent rolebans to VileSlugcat  Sawmill=admin.bans |  
  |   | 2024-06-30 19:16:32.453 | Completing handshake with VileSlugcat.  Sawmill=szr |  
  |   | 2024-06-30 19:16:32.453 | Received handshake from VileSlugcat.  Sawmill=szr |  
  |   | 2024-06-30 19:16:31.191 | Sending 1054538 bytes sized mapped strings package to VileSlugcat.  Sawmill=szr |  
  |   | 2024-06-30 19:16:31.191 | Received handshake from VileSlugcat.  Sawmill=szr |  
  |   | 2024-06-30 19:16:31.123 | Approved [REDACTED] with username VileSlugcat into the server  ConnectionEndpoint=[REDACTED] Username=VileSlugcat Sawmill=net
```

@deltanedas

**Comment by pissdemon** [comment]
This is complete speculation, but is it possible that a race condition is triggering this?

**Comment by Axionyxx** [comment]
I've looked at some additional data, and I think this might potentially be the cause, based on more speculation.

The current selected profile for the player who's listen in the exception has `pref_unavailable` set to `StayInLobby`. That profile only has these preferences set
![image](https://github.com/DeltaV-Station/Delta-v/assets/56081759/36a97209-ef2c-4a6d-9dcc-2001926fb0c7)

Its possible that none of those slots were left by the time they got picked, and the game in turn left them in the lobby. I'll see if the spawning is logged in the admin logs that early on

**Comment by Axionyxx** [comment]
I can't confirm if it was that. Admin logs aren't recorded during that stage

**Comment by deltanedas** [comment]
wont matter after upstream merge which changes it to error logs

**Comment by Axionyxx** [comment]
> wont matter after upstream merge which changes it to error logs

Wdym?

**Comment by deltanedas** [comment]
instead of throwing and preventing the round from starting it just logs it and continues without a thief

**Comment by ghost** [comment]
Upstream merge has been merged by now, probably, so it probably does this. I haven't seen it throw in a while. Therefore, closing this.
