### ISSUE TITLE
Invisibility bug 

### ISSUE THREAD

**Issue by verrsc** [DeltaV-Station/Delta-v#1585]
## Description
I've had a situation where upon using the chameleon projector and getting locked in one of those large animal crates, upon exiting, you become invincible. What I mean is, you are still prone to getting discovered, but there is no model or any distortion visible when you move, so you are like a ghost.

**Reproduction**
1 Use chameleon projector (Probably any item works, but I've done it with one of those long portable lamps)
2 Position yourself over crate (Once again, most likely any crate works, but I've done it only on the animal box)
3 Have someone lock it, then unlock it
4 Exit the crate, and have no model attached to you

**Screenshots**
Sorry! Forgot to take a screenshot

**Additional context**
N/A

**Comment by DisposableCrewmember42** [comment]
Able to reproduce this in a dev env.

1. Use Chameleon Projector
2. Stand on top of a crate
3. Close and open it
4. Step out

Observations:
- There is no model attached to the player and they can move around invisibly
- They regain their original model once they are no longer holding the projector in their primary hand and the detached entity is deleted
- Picking up the detached chameleon item using another character triggers a server crash

```
[FATL] unhandled: System.ArgumentException: Entity 2578 is not valid. (Parameter 'uid')
   at Robust.Shared.GameObjects.EntityManager.AddComponent[T](EntityUid uid, T component, Boolean overwrite, MetaDataComponent metadata) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityManager.Components.cs:line 316
   at Robust.Shared.GameObjects.EntityManager.AddComponent[T](EntityUid uid) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityManager.Components.cs:line 244
   at Content.Server.Abilities.Oni.OniSystem.OnEntInserted(EntityUid uid, OniComponent component, EntInsertedIntoContainerMessage args) in /home/user/Delta-v/Content.Server/Nyanotrasen/Abilities/Oni/OniSystem.cs:line 29
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass54_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 272
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass67_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 460
   at Robust.Shared.GameObjects.EntityEventBus.EntDispatch(EntityUid euid, Type eventType, Unit& args) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 634
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEventCore(EntityUid uid, Unit& unitRef, Type type, Boolean broadcast) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 240
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 200
   at Robust.Shared.GameObjects.EntitySystem.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntitySystem.cs:line 159
   at Robust.Shared.Containers.SharedContainerSystem.Insert(Entity`3 toInsert, BaseContainer container, TransformComponent containerXform, Boolean force) in /home/user/Delta-v/RobustToolbox/Robust.Shared/Containers/SharedContainerSystem.Insert.cs:line 124
   at Content.Shared.Hands.EntitySystems.SharedHandsSystem.DoPickup(EntityUid uid, Hand hand, EntityUid entity, HandsComponent hands) in /home/user/Delta-v/Content.Shared/Hands/EntitySystems/SharedHandsSystem.Pickup.cs:line 232
   at Content.Shared.Hands.EntitySystems.SharedHandsSystem.TryPickup(EntityUid uid, EntityUid entity, Hand hand, Boolean checkActionBlocker, Boolean animate, HandsComponent handsComp, ItemComponent item) in /home/user/Delta-v/Content.Shared/Hands/EntitySystems/SharedHandsSystem.Pickup.cs:line 122
   at Content.Shared.Hands.EntitySystems.SharedHandsSystem.TryPickup(EntityUid uid, EntityUid entity, String handName, Boolean checkActionBlocker, Boolean animateUser, Boolean animate, HandsComponent handsComp, ItemComponent item) in /home/user/Delta-v/Content.Shared/Hands/EntitySystems/SharedHandsSystem.Pickup.cs:line 61
   at Content.Shared.Item.SharedItemSystem.OnHandInteract(EntityUid uid, ItemComponent component, InteractHandEvent args) in /home/user/Delta-v/Content.Shared/Item/SharedItemSystem.cs:line 94
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass54_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 272
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass67_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 460
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass76_1.<EntCollectOrdered>b__0(Unit& ev) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 664
   at Robust.Shared.GameObjects.EntityEventBus.DispatchOrderedEvents(Unit& eventArgs, ValueList`1& found) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Ordering.cs:line 52
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalOrdered(EntityUid uid, Type eventType, EventData subs, Unit& unitRef, Boolean broadcast) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Ordering.cs:line 43
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEventCore(EntityUid uid, Unit& unitRef, Type type, Boolean broadcast) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 236
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 200
   at Robust.Shared.GameObjects.EntitySystem.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntitySystem.cs:line 159
   at Content.Shared.Interaction.SharedInteractionSystem.InteractHand(EntityUid user, EntityUid target) in /home/user/Delta-v/Content.Shared/Interaction/SharedInteractionSystem.cs:line 465
   at Content.Shared.Interaction.SharedInteractionSystem.UserInteraction(EntityUid user, EntityCoordinates coordinates, Nullable`1 target, Boolean altInteract, Boolean checkCanInteract, Boolean checkAccess, Boolean checkCanUse) in /home/user/Delta-v/Content.Shared/Interaction/SharedInteractionSystem.cs:line 408
   at Content.Shared.Interaction.SharedInteractionSystem.HandleUseInteraction(ICommonSession session, EntityCoordinates coords, EntityUid uid) in /home/user/Delta-v/Content.Shared/Interaction/SharedInteractionSystem.cs:line 295
   at Robust.Shared.Input.Binding.PointerInputCmdHandler.<>c__DisplayClass5_0.<.ctor>b__0(PointerInputCmdArgs& args) in /home/user/Delta-v/RobustToolbox/Robust.Shared/Input/Binding/InputCmdHandler.cs:line 97
   at Robust.Shared.Input.Binding.PointerInputCmdHandler.HandleCmdMessage(IEntityManager entManager, ICommonSession session, IFullInputCmdMessage message) in /home/user/Delta-v/RobustToolbox/Robust.Shared/Input/Binding/InputCmdHandler.cs:line 127
   at Robust.Server.GameObjects.InputSystem.InputMessageHandler(InputCmdMessage message, EntitySessionEventArgs eventArgs) in /home/user/Delta-v/RobustToolbox/Robust.Server/GameObjects/EntitySystems/InputSystem.cs:line 65
   at Robust.Shared.GameObjects.EventBusExt.HandlerWrapper`1.Invoke(EntitySessionMessage`1 msg) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EventBusExt.cs:line 46
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass4_0`1.<SubscribeEvent>b__0(Unit& ev) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 173
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 335
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Unit& unitRef, Type eventType) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 324
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent(EventSource source, Object toRaise) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 267
   at Robust.Server.GameObjects.ServerEntityManager.<Initialize>b__8_0(Object _, Object systemMsg) in /home/user/Delta-v/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 53
   at Robust.Server.GameObjects.ServerEntityManager.DispatchEntityNetworkMessage(MsgEntity message) in /home/user/Delta-v/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 266
   at Robust.Server.GameObjects.ServerEntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in /home/user/Delta-v/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 192
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in /home/user/Delta-v/RobustToolbox/Robust.Server/BaseServer.cs:line 731
   at Robust.Server.BaseServer.<SetupMainLoop>b__67_1(Object sender, FrameEventArgs args) in /home/user/Delta-v/RobustToolbox/Robust.Server/BaseServer.cs:line 544
   at Robust.Shared.Timing.GameLoop.Run() in /home/user/Delta-v/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 235
   at Robust.Server.BaseServer.MainLoop() in /home/user/Delta-v/RobustToolbox/Robust.Server/BaseServer.cs:line 571
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options) in /home/user/Delta-v/RobustToolbox/Robust.Server/Program.cs:line 74
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart) in /home/user/Delta-v/RobustToolbox/Robust.Server/Program.cs:line 42
   at Robust.Server.ContentStart.Start(String[] args) in /home/user/Delta-v/RobustToolbox/Robust.Server/ContentStart.cs:line 10
   at Content.Server.Program.Main(String[] args) in /home/user/Delta-v/Content.Server/Program.cs:line 9
Unhandled exception. System.ArgumentException: Entity 2578 is not valid. (Parameter 'uid')
   at Robust.Shared.GameObjects.EntityManager.AddComponent[T](EntityUid uid, T component, Boolean overwrite, MetaDataComponent metadata) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityManager.Components.cs:line 316
   at Robust.Shared.GameObjects.EntityManager.AddComponent[T](EntityUid uid) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityManager.Components.cs:line 244
   at Content.Server.Abilities.Oni.OniSystem.OnEntInserted(EntityUid uid, OniComponent component, EntInsertedIntoContainerMessage args) in /home/user/Delta-v/Content.Server/Nyanotrasen/Abilities/Oni/OniSystem.cs:line 29
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass54_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 272
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass67_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 460
   at Robust.Shared.GameObjects.EntityEventBus.EntDispatch(EntityUid euid, Type eventType, Unit& args) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 634
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEventCore(EntityUid uid, Unit& unitRef, Type type, Boolean broadcast) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 240
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 200
   at Robust.Shared.GameObjects.EntitySystem.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntitySystem.cs:line 159
   at Robust.Shared.Containers.SharedContainerSystem.Insert(Entity`3 toInsert, BaseContainer container, TransformComponent containerXform, Boolean force) in /home/user/Delta-v/RobustToolbox/Robust.Shared/Containers/SharedContainerSystem.Insert.cs:line 124
   at Content.Shared.Hands.EntitySystems.SharedHandsSystem.DoPickup(EntityUid uid, Hand hand, EntityUid entity, HandsComponent hands) in /home/user/Delta-v/Content.Shared/Hands/EntitySystems/SharedHandsSystem.Pickup.cs:line 232
   at Content.Shared.Hands.EntitySystems.SharedHandsSystem.TryPickup(EntityUid uid, EntityUid entity, Hand hand, Boolean checkActionBlocker, Boolean animate, HandsComponent handsComp, ItemComponent item) in /home/user/Delta-v/Content.Shared/Hands/EntitySystems/SharedHandsSystem.Pickup.cs:line 122
   at Content.Shared.Hands.EntitySystems.SharedHandsSystem.TryPickup(EntityUid uid, EntityUid entity, String handName, Boolean checkActionBlocker, Boolean animateUser, Boolean animate, HandsComponent handsComp, ItemComponent item) in /home/user/Delta-v/Content.Shared/Hands/EntitySystems/SharedHandsSystem.Pickup.cs:line 61
   at Content.Shared.Item.SharedItemSystem.OnHandInteract(EntityUid uid, ItemComponent component, InteractHandEvent args) in /home/user/Delta-v/Content.Shared/Item/SharedItemSystem.cs:line 94
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass54_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 272
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass67_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 460
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass76_1.<EntCollectOrdered>b__0(Unit& ev) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 664
   at Robust.Shared.GameObjects.EntityEventBus.DispatchOrderedEvents(Unit& eventArgs, ValueList`1& found) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Ordering.cs:line 52
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalOrdered(EntityUid uid, Type eventType, EventData subs, Unit& unitRef, Boolean broadcast) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Ordering.cs:line 43
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEventCore(EntityUid uid, Unit& unitRef, Type type, Boolean broadcast) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 236
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 200
   at Robust.Shared.GameObjects.EntitySystem.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntitySystem.cs:line 159
   at Content.Shared.Interaction.SharedInteractionSystem.InteractHand(EntityUid user, EntityUid target) in /home/user/Delta-v/Content.Shared/Interaction/SharedInteractionSystem.cs:line 465
   at Content.Shared.Interaction.SharedInteractionSystem.UserInteraction(EntityUid user, EntityCoordinates coordinates, Nullable`1 target, Boolean altInteract, Boolean checkCanInteract, Boolean checkAccess, Boolean checkCanUse) in /home/user/Delta-v/Content.Shared/Interaction/SharedInteractionSystem.cs:line 408
   at Content.Shared.Interaction.SharedInteractionSystem.HandleUseInteraction(ICommonSession session, EntityCoordinates coords, EntityUid uid) in /home/user/Delta-v/Content.Shared/Interaction/SharedInteractionSystem.cs:line 295
   at Robust.Shared.Input.Binding.PointerInputCmdHandler.<>c__DisplayClass5_0.<.ctor>b__0(PointerInputCmdArgs& args) in /home/user/Delta-v/RobustToolbox/Robust.Shared/Input/Binding/InputCmdHandler.cs:line 97
   at Robust.Shared.Input.Binding.PointerInputCmdHandler.HandleCmdMessage(IEntityManager entManager, ICommonSession session, IFullInputCmdMessage message) in /home/user/Delta-v/RobustToolbox/Robust.Shared/Input/Binding/InputCmdHandler.cs:line 127
   at Robust.Server.GameObjects.InputSystem.InputMessageHandler(InputCmdMessage message, EntitySessionEventArgs eventArgs) in /home/user/Delta-v/RobustToolbox/Robust.Server/GameObjects/EntitySystems/InputSystem.cs:line 65
   at Robust.Shared.GameObjects.EventBusExt.HandlerWrapper`1.Invoke(EntitySessionMessage`1 msg) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EventBusExt.cs:line 46
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass4_0`1.<SubscribeEvent>b__0(Unit& ev) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 173
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 335
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Unit& unitRef, Type eventType) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 324
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent(EventSource source, Object toRaise) in /home/user/Delta-v/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Broadcast.cs:line 267
   at Robust.Server.GameObjects.ServerEntityManager.<Initialize>b__8_0(Object _, Object systemMsg) in /home/user/Delta-v/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 53
   at Robust.Server.GameObjects.ServerEntityManager.DispatchEntityNetworkMessage(MsgEntity message) in /home/user/Delta-v/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 266
   at Robust.Server.GameObjects.ServerEntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in /home/user/Delta-v/RobustToolbox/Robust.Server/GameObjects/ServerEntityManager.cs:line 192
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in /home/user/Delta-v/RobustToolbox/Robust.Server/BaseServer.cs:line 731
   at Robust.Server.BaseServer.<SetupMainLoop>b__67_1(Object sender, FrameEventArgs args) in /home/user/Delta-v/RobustToolbox/Robust.Server/BaseServer.cs:line 544
   at Robust.Shared.Timing.GameLoop.Run() in /home/user/Delta-v/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 235
   at Robust.Server.BaseServer.MainLoop() in /home/user/Delta-v/RobustToolbox/Robust.Server/BaseServer.cs:line 571
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options) in /home/user/Delta-v/RobustToolbox/Robust.Server/Program.cs:line 74
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart) in /home/user/Delta-v/RobustToolbox/Robust.Server/Program.cs:line 42
   at Robust.Server.ContentStart.Start(String[] args) in /home/user/Delta-v/RobustToolbox/Robust.Server/ContentStart.cs:line 10
   at Content.Server.Program.Main(String[] args) in /home/user/Delta-v/Content.Server/Program.cs:line 9
   ```
Will follow up with video

**Comment by DisposableCrewmember42** [comment]
This does require a few tries sometimes, which makes me think it may be a race condition, fun!

Here's a video:

https://github.com/user-attachments/assets/404c4477-bc7e-4412-9daf-76ae66c7dbd1

**Comment by deltanedas** [comment]
its just a mispredict with crate opening and projector shit, a lot of items do that

**Comment by deltanedas** [comment]
ok not a mispredict
when you close a crate the crate reparents the disguise to it for whatever reason, which makes the disguise just not move with you
